SavePath: "Final/data/PhoneSpecsBatch/"
files: "Devices_Specs"

conversion_rates: { "$": 0.94, "£": 1.15, "₹": 0.011 }

regressors:
  [
    "LinearRegression",
    "Ridge",
    "Lasso",
    "ElasticNet",
    "RandomForestRegressor",
    "SGDRegressor",
    "DecisionTreeRegressor",
    "KNeighborsRegressor",
    "GradientBoostingRegressor",
    "ExtraTreesRegressor",
    "XGBRegressor",
  ]

variables:
  [
    "Brand",
    "NETWORK_2G_bands",
    "NETWORK_3G_bands",
    "NETWORK_4G_bands",
    "NETWORK_5G_bands",
    "NETWORK_Speed",
    "NETWORK_Technology",
  ]

fillna_retrain_variables:
  [
    "NETWORK_2G_bands",
    "NETWORK_3G_bands",
    "NETWORK_4G_bands",
    "NETWORK_5G_bands",
    "NETWORK_Speed",
    "NETWORK_Technology",
  ]

target: "MISC_Price_Euro"

test_size: 0.3
